const nodes = [
  {
    nodeId: '1003',
    parentNodeId: null,
    rawId: null,
    groupId: null,
    nodeType: null,
    sortId: null,
    nodeName: '首页',
    icon: 'SwapOutlined',
    leaf: false,
    nodeData: {
      menuCode: '1003',
      menuName: '首页',
      menuDesc: '首页',
      menuUrl: '/dashboard',
      menuType: 1,
      buttonUrlId: 0,
      parentMenuCode: '1',
      createTime: '2022-09-08 14:38:14',
      updateTime: '2023-01-30 15:47:41',
      icon: 'SwapOutlined',
      sortId: 1,
      state: 1,
      urlPath: null,
      urlName: null,
      invokeMode: 0,
      methodType: null,
    },
  },
  {
    nodeId: '1001',
    parentNodeId: null,
    rawId: null,
    groupId: null,
    nodeType: null,
    sortId: null,
    nodeName: '系统管理',
    icon: 'TagsOutlined',
    leaf: false,
    nodeData: {
      menuCode: '1001',
      menuName: '系统管理',
      menuDesc: '系统管理',
      menuUrl: '/system',
      menuType: 0,
      buttonUrlId: 0,
      parentMenuCode: '1',
      createTime: '2019-02-13 15:52:40',
      updateTime: '2022-11-04 09:30:46',
      icon: 'TagsOutlined',
      sortId: 3,
      state: 1,
      urlPath: null,
      urlName: null,
      invokeMode: 0,
      methodType: null,
    },
    parents: null,
    children: [
      {
        nodeId: '1001018',
        parentNodeId: null,
        rawId: null,
        groupId: null,
        nodeType: null,
        sortId: null,
        nodeName: '菜单管理',
        icon: null,
        leaf: false,
        nodeData: {
          menuCode: '1001018',
          menuName: '菜单管理',
          menuDesc: '菜单管理',
          menuUrl: '/system/menu',
          menuType: 1,
          buttonUrlId: 0,
          parentMenuCode: '1001',
          createTime: '2022-09-13 15:28:31',
          updateTime: '2022-09-13 15:32:48',
          icon: null,
          sortId: 1,
          state: 1,
          urlPath: null,
          urlName: null,
          invokeMode: 0,
          methodType: null,
        },
        children: [
          {
            nodeId: '1001018001',
            parentNodeId: null,
            rawId: null,
            groupId: null,
            nodeType: null,
            sortId: null,
            nodeName: '查询列表',
            icon: '',
            leaf: true,
            nodeData: {
              menuCode: '1001018001',
              menuName: '查询列表',
              menuDesc: '查询列表',
              menuUrl: 'sys:configuration:list',
              menuType: 2,
              buttonUrlId: 54,
              parentMenuCode: '1001018001',
              createTime: '2022-09-14 09:57:07',
              updateTime: '2022-11-03 10:56:20',
              icon: '',
              sortId: 1,
              state: 1,
              urlPath: '',
              urlName: '角色配置-查询列表',
              invokeMode: 0,
              methodType: null,
            },
            parents: null,
            children: [],
            urlList: [],
          },
        ],
      },
      {
        nodeId: '1001002',
        parentNodeId: null,
        rawId: null,
        groupId: null,
        nodeType: null,
        sortId: null,
        nodeName: '字典管理',
        icon: '',
        leaf: false,
        nodeData: {
          menuCode: '1001002',
          menuName: '字典管理',
          menuDesc: '',
          menuUrl: '/system/dictionary',
          menuType: 1,
          buttonUrlId: 0,
          parentMenuCode: '1001',
          createTime: '2019-02-13 15:52:40',
          updateTime: '2022-04-16 13:59:44',
          icon: '',
          sortId: 2,
          state: 1,
          urlPath: null,
          urlName: null,
          invokeMode: 0,
          methodType: null,
        },
        parents: null,
        children: [
          {
            nodeId: '1001002001',
            parentNodeId: null,
            rawId: null,
            groupId: null,
            nodeType: null,
            sortId: null,
            nodeName: '查询',
            icon: null,
            leaf: true,
            nodeData: {
              menuCode: '1001002001',
              menuName: '查询',
              menuDesc: '角色查询',
              menuUrl: 'sys:role:list',
              menuType: 2,
              buttonUrlId: 10000,
              parentMenuCode: '1001002',
              createTime: '2021-08-24 14:49:26',
              updateTime: '2021-08-24 14:49:26',
              icon: null,
              sortId: 0,
              state: 1,
              urlPath: '',
              urlName: '角色查询',
              invokeMode: 0,
              methodType: null,
            },
            parents: null,
            children: [],
            urlList: [],
          },
          {
            nodeId: '1001002003',
            parentNodeId: null,
            rawId: null,
            groupId: null,
            nodeType: null,
            sortId: null,
            nodeName: '编辑',
            icon: null,
            leaf: true,
            nodeData: {
              menuCode: '1001002003',
              menuName: '编辑',
              menuDesc: '角色修改',
              menuUrl: 'sys:role:update',
              menuType: 2,
              buttonUrlId: 10011,
              parentMenuCode: '1001002',
              createTime: '2021-08-25 09:15:10',
              updateTime: '2021-08-27 09:01:04',
              icon: null,
              sortId: 0,
              state: 1,
              urlPath: '',
              urlName: '角色修改',
              invokeMode: 0,
              methodType: null,
            },
            parents: null,
            children: [],
            urlList: [],
          },
        ],
      },
      {
        nodeId: '1001019',
        parentNodeId: null,
        rawId: null,
        groupId: null,
        nodeType: null,
        sortId: null,
        nodeName: '人员管理',
        icon: null,
        leaf: false,
        nodeData: {
          menuCode: '1001019',
          menuName: '人员管理',
          menuDesc: '人员管理',
          menuUrl: '/system/user',
          menuType: 1,
          buttonUrlId: 0,
          parentMenuCode: '1001',
          createTime: '2022-09-16 09:19:57',
          updateTime: '2022-11-03 11:09:55',
          icon: null,
          sortId: 3,
          state: 1,
          urlPath: null,
          urlName: null,
          invokeMode: 0,
          methodType: null,
        },
        parents: null,
        children: [
          {
            nodeId: '1001019001',
            parentNodeId: null,
            rawId: null,
            groupId: null,
            nodeType: null,
            sortId: null,
            nodeName: '查询列表',
            icon: null,
            leaf: true,
            nodeData: {
              menuCode: '1001019001',
              menuName: '查询列表',
              menuDesc: '查询列表',
              menuUrl: 'sys:modifyLog:list',
              menuType: 2,
              buttonUrlId: 57,
              parentMenuCode: '1001019',
              createTime: '2022-09-16 09:33:31',
              updateTime: '2022-11-03 11:10:13',
              icon: null,
              sortId: 1,
              state: 1,
              urlPath: null,
              urlName: '人员权限修改日志-查询列表',
              invokeMode: 0,
              methodType: null,
            },
            parents: null,
            children: [],
            urlList: [],
          },
        ],
        urlList: [],
      },
      {
        nodeId: '1001001',
        parentNodeId: null,
        rawId: null,
        groupId: null,
        nodeType: null,
        sortId: null,
        nodeName: '角色管理',
        icon: '',
        leaf: false,
        nodeData: {
          menuCode: '1001001',
          menuName: '角色管理',
          menuDesc: '',
          menuUrl: '/system/role',
          menuType: 1,
          buttonUrlId: 0,
          parentMenuCode: '1001',
          createTime: '2019-02-13 15:52:41',
          updateTime: '2022-09-16 09:22:45',
          icon: '',
          sortId: 4,
          state: 1,
          urlPath: null,
          urlName: null,
          invokeMode: 0,
          methodType: null,
        },
        parents: null,
        children: [],
        urlList: [],
      },
      {
        nodeId: '1001006',
        parentNodeId: null,
        rawId: null,
        groupId: null,
        nodeType: null,
        sortId: null,
        nodeName: '组织管理',
        icon: null,
        leaf: false,
        nodeData: {
          menuCode: '1001006',
          menuName: '组织管理',
          menuDesc: null,
          menuUrl: '/system/org',
          menuType: 1,
          buttonUrlId: 0,
          parentMenuCode: '1001',
          createTime: '2021-04-27 15:44:35',
          updateTime: '2022-09-16 09:21:47',
          icon: null,
          sortId: 5,
          state: 1,
          urlPath: null,
          urlName: null,
          invokeMode: 0,
          methodType: null,
        },
        parents: null,
        children: [
          {
            nodeId: '1001006005',
            parentNodeId: null,
            rawId: null,
            groupId: null,
            nodeType: null,
            sortId: null,
            nodeName: '查询',
            icon: null,
            leaf: true,
            nodeData: {
              menuCode: '1001006005',
              menuName: '查询',
              menuDesc: '组织列表查询',
              menuUrl: 'sys:org:list',
              menuType: 2,
              buttonUrlId: 0,
              parentMenuCode: '1001006',
              createTime: '2022-09-07 11:16:00',
              updateTime: '2022-09-07 11:16:00',
              icon: null,
              sortId: 2,
              state: 1,
              urlPath: null,
              urlName: null,
              invokeMode: 0,
              methodType: null,
            },
            parents: null,
            children: [],
            urlList: [],
          },
          {
            nodeId: '1001006006',
            parentNodeId: null,
            rawId: null,
            groupId: null,
            nodeType: null,
            sortId: null,
            nodeName: '新增',
            icon: null,
            leaf: true,
            nodeData: {
              menuCode: '1001006006',
              menuName: '新增',
              menuDesc: '组织新增',
              menuUrl: 'sys:org:create',
              menuType: 2,
              buttonUrlId: 0,
              parentMenuCode: '1001006',
              createTime: '2022-09-07 11:16:31',
              updateTime: '2022-09-07 11:16:31',
              icon: null,
              sortId: 3,
              state: 1,
              urlPath: null,
              urlName: null,
              invokeMode: 0,
              methodType: null,
            },
            parents: null,
            children: [],
            urlList: [],
          },
        ],
        urlList: [],
      },
    ],
    urlList: [],
  },
  {
    nodeId: '1004',
    parentNodeId: null,
    rawId: null,
    groupId: null,
    nodeType: null,
    sortId: null,
    nodeName: '多级菜单',
    icon: 'SettingFilled',
    leaf: false,
    nodeData: {
      menuCode: '1004',
      menuName: '多级菜单',
      menuDesc: '多级菜单',
      menuUrl: '/nested',
      menuType: 0,
      buttonUrlId: 0,
      parentMenuCode: '1',
      createTime: '2022-09-15 09:03:24',
      updateTime: '2022-09-15 09:11:08',
      icon: 'SettingFilled',
      sortId: 4,
      state: 1,
      urlPath: null,
      urlName: null,
      invokeMode: 0,
      methodType: null,
    },
    parents: null,
    children: [
      {
        nodeId: '1004012',
        parentNodeId: null,
        rawId: null,
        groupId: null,
        nodeType: null,
        sortId: null,
        nodeName: '菜单1',
        icon: '',
        leaf: false,
        nodeData: {
          menuCode: '1004012',
          menuName: '菜单1',
          menuDesc: '菜单1',
          menuUrl: '/nested/menu1/menu1-1',
          menuType: 1,
          buttonUrlId: 0,
          parentMenuCode: '1004012',
          createTime: '2019-05-15 14:47:24',
          updateTime: '2022-09-15 09:10:37',
          icon: '',
          sortId: 0,
          state: 1,
          urlPath: null,
          urlName: null,
          invokeMode: 0,
          methodType: null,
        },
        parents: null,
        children: [
          {
            nodeId: '1004011',
            parentNodeId: null,
            rawId: null,
            groupId: null,
            nodeType: null,
            sortId: null,
            nodeName: '菜单1-1',
            icon: null,
            leaf: false,
            nodeData: {
              menuCode: '1004011',
              menuName: '菜单1-1',
              menuDesc: '菜单1-1',
              menuUrl: '/nested/menu1-1',
              menuType: 1,
              buttonUrlId: 0,
              parentMenuCode: '1004012',
              createTime: '2022-10-26 09:22:01',
              updateTime: '2022-10-26 09:22:01',
              icon: null,
              sortId: 1,
              state: 1,
              urlPath: null,
              urlName: null,
              invokeMode: 0,
              methodType: null,
            },
            parents: null,
            children: [],
            urlList: [],
          },
          {
            nodeId: '10040123',
            parentNodeId: null,
            rawId: null,
            groupId: null,
            nodeType: null,
            sortId: null,
            nodeName: '菜单1-2',
            icon: null,
            leaf: false,
            nodeData: {
              menuCode: '10040123',
              menuName: '菜单1-2',
              menuDesc: '菜单1-2',
              menuUrl: '/nested/menu1/menu1-2',
              menuType: 1,
              buttonUrlId: 0,
              parentMenuCode: '1004012',
              createTime: '2022-10-26 09:22:01',
              updateTime: '2022-10-26 09:22:01',
              icon: null,
              sortId: 1,
              state: 1,
              urlPath: null,
              urlName: null,
              invokeMode: 0,
              methodType: null,
            },
            parents: null,
            children: [
              {
                nodeId: '10040131',
                parentNodeId: null,
                rawId: null,
                groupId: null,
                nodeType: null,
                sortId: null,
                nodeName: '菜单1-2-1',
                icon: null,
                leaf: false,
                nodeData: {
                  menuCode: '10040131',
                  menuName: '菜单1-2-1',
                  menuDesc: '菜单1-2-1',
                  menuUrl: '/nested/menu1/menu1-2/menu1-2-1',
                  menuType: 1,
                  buttonUrlId: 0,
                  parentMenuCode: '1004',
                  createTime: '2022-10-26 09:22:01',
                  updateTime: '2022-10-26 09:22:01',
                  icon: null,
                  sortId: 1,
                  state: 1,
                  urlPath: null,
                  urlName: null,
                  invokeMode: 0,
                  methodType: null,
                },
                parents: null,
                children: [],
                urlList: [],
              },
              {
                nodeId: '100401366',
                parentNodeId: null,
                rawId: null,
                groupId: null,
                nodeType: null,
                sortId: null,
                nodeName: '菜单1-2-2',
                icon: null,
                leaf: false,
                nodeData: {
                  menuCode: '100401366',
                  menuName: '菜单1-2-2',
                  menuDesc: '菜单1-2-2',
                  menuUrl: '/nested/menu1/menu1-2/menu1-2-2',
                  menuType: 1,
                  buttonUrlId: 0,
                  parentMenuCode: '1004',
                  createTime: '2022-10-26 09:22:01',
                  updateTime: '2022-10-26 09:22:01',
                  icon: null,
                  sortId: 1,
                  state: 1,
                  urlPath: null,
                  urlName: null,
                  invokeMode: 0,
                  methodType: null,
                },
                parents: null,
                children: [],
                urlList: [],
              },
            ],
            urlList: [],
          },
          {
            nodeId: '1004013',
            parentNodeId: null,
            rawId: null,
            groupId: null,
            nodeType: null,
            sortId: null,
            nodeName: '菜单1-3',
            icon: null,
            leaf: false,
            nodeData: {
              menuCode: '1004013',
              menuName: '菜单1-3',
              menuDesc: '菜单1-3',
              menuUrl: '/nested/menu1-3',
              menuType: 1,
              buttonUrlId: 0,
              parentMenuCode: '1004',
              createTime: '2022-10-26 09:22:01',
              updateTime: '2022-10-26 09:22:01',
              icon: null,
              sortId: 1,
              state: 1,
              urlPath: null,
              urlName: null,
              invokeMode: 0,
              methodType: null,
            },
            parents: null,
            children: [],
            urlList: [],
          },
        ],
        urlList: [],
      },
      {
        nodeId: '1004014',
        parentNodeId: null,
        rawId: null,
        groupId: null,
        nodeType: null,
        sortId: null,
        nodeName: '菜单2',
        icon: null,
        leaf: false,
        nodeData: {
          menuCode: '1004014',
          menuName: '菜单2',
          menuDesc: '菜单2',
          menuUrl: '/nested/menu2',
          menuType: 1,
          buttonUrlId: 0,
          parentMenuCode: '1004',
          createTime: '2022-10-26 09:22:01',
          updateTime: '2022-10-26 09:22:01',
          icon: null,
          sortId: 1,
          state: 1,
          urlPath: null,
          urlName: null,
          invokeMode: 0,
          methodType: null,
        },
        parents: null,
        children: [],
        urlList: [],
      },
    ],
    urlList: [],
  },
  {
    nodeId: '10056',
    parentNodeId: null,
    rawId: null,
    groupId: null,
    nodeType: null,
    sortId: null,
    nodeName: '列表页',
    icon: 'BarChartOutlined',
    leaf: false,
    nodeData: {
      menuCode: '10056',
      menuName: '列表页',
      menuDesc: '列表页',
      menuUrl: '/table',
      menuType: 0,
      buttonUrlId: 0,
      parentMenuCode: '1',
      createTime: '2022-09-27 10:26:30',
      updateTime: '2022-11-04 09:29:59',
      icon: 'BarChartOutlined',
      sortId: 5,
      state: 1,
      urlPath: null,
      urlName: null,
      invokeMode: 0,
      methodType: null,
    },
    parents: null,
    children: [
      {
        nodeId: '1005001',
        parentNodeId: null,
        rawId: null,
        groupId: null,
        nodeType: null,
        sortId: null,
        nodeName: '基础列表',
        icon: null,
        leaf: false,
        nodeData: {
          menuCode: '1005001',
          menuName: '基础列表',
          menuDesc: null,
          menuUrl: '/table/basic-table',
          menuType: 1,
          buttonUrlId: 0,
          parentMenuCode: '1005',
          createTime: '2022-09-27 10:42:29',
          updateTime: '2022-09-27 10:42:29',
          icon: null,
          sortId: 1,
          state: 1,
          urlPath: null,
          urlName: null,
          invokeMode: 0,
          methodType: null,
        },
        parents: null,
        children: [],
        urlList: [],
      },
    ],
    urlList: [],
  },
  {
    nodeId: '1004555',
    parentNodeId: null,
    rawId: null,
    groupId: null,
    nodeType: null,
    sortId: null,
    nodeName: '个人页',
    icon: 'BarChartOutlined',
    leaf: false,
    nodeData: {
      menuCode: '1004555',
      menuName: '个人页',
      menuDesc: '个人页',
      menuUrl: '/account',
      menuType: 0,
      buttonUrlId: 0,
      parentMenuCode: '1',
      createTime: '2022-09-27 10:26:30',
      updateTime: '2022-11-04 09:29:59',
      icon: 'BarChartOutlined',
      sortId: 5,
      state: 1,
      urlPath: null,
      urlName: null,
      invokeMode: 0,
      methodType: null,
    },
    parents: null,
    children: [
      {
        nodeId: '1005002',
        parentNodeId: null,
        rawId: null,
        groupId: null,
        nodeType: null,
        sortId: null,
        nodeName: '个人设置',
        icon: null,
        leaf: false,
        nodeData: {
          menuCode: '1005002',
          menuName: '个人设置',
          menuDesc: null,
          menuUrl: '/account/settings',
          menuType: 1,
          buttonUrlId: 0,
          parentMenuCode: '1005002',
          createTime: '2022-09-27 10:42:29',
          updateTime: '2022-09-27 10:42:29',
          icon: null,
          sortId: 1,
          state: 1,
          urlPath: null,
          urlName: null,
          invokeMode: 0,
          methodType: null,
        },
        parents: null,
        children: [],
        urlList: [],
      },
    ],
    urlList: [],
  },
];

const checkedIds = [
  '1003',
  '1001018',
  '1001002',
  '1001019',
  '1001001',
  '1001006',
  '1001002003',
  '1001002001',
  '1001006005',
  '1001006006',
  '1001018001',
  '1001019001',
  '1004012',
  '1004014',
  '1005001',
  '10040131',
  '1004013',
  '1001',
  '1004',
  '1004555',
  '10056',
];

const RoleMenuDatas = {
  nodes,
  checkedIds,
};

export default RoleMenuDatas;
